[package]
name = "async-core"
version = "0.3.1"
edition = "2021"
repository = "https://github.com/tudbut/async-core"
license = "MIT"
description = "A standard for async runtimes"
categories = ["async", "no-std"]

[dependencies]

[features]
no_std = []
